### ISSUE TITLE
Issues installing package from Github in R

### ISSUE THREAD

**Issue by ryanhum** [immunogenomics/GPROB#1]
Hi - I am trying to install GPROB in R but am getting the following error message:

> devtools::install_github("immunogenomics/GPROB")
Downloading GitHub repo immunogenomics/GPROB@HEAD
✓  checking for file ‘/private/var/folders/kn/m9lgxb4s3qs7dxrrbn6dz8lw0000gn/T/RtmppwSa3f/remotes181734966613/immunogenomics-GPROB-70327f1/DESCRIPTION’ ...
─  preparing ‘GPROB’:
✓  checking DESCRIPTION meta-information ...
─  installing the package to process help pages
         -----------------------------------
─  installing *source* package ‘GPROB’ ...
   ** using staged installation
   ** R
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error in nlminb(3, obj) : object 'obj' not found
   Error: unable to load R code in package ‘GPROB’
   Execution halted
   ERROR: lazy loading failed for package ‘GPROB’
─  removing ‘/private/var/folders/kn/m9lgxb4s3qs7dxrrbn6dz8lw0000gn/T/RtmpcmQSQn/Rinst1892411df3b5/GPROB’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'GPROB' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** R
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Error in nlminb(3, obj) : object 'obj' not found
E> Error: unable to load R code in package ‘GPROB’
E> Execution halted
E> ERROR: lazy loading failed for package ‘GPROB’
E> * removing ‘/private/var/folders/kn/m9lgxb4s3qs7dxrrbn6dz8lw0000gn/T/RtmpcmQSQn/Rinst1892411df3b5/GPROB’
E>       -----------------------------------
E> ERROR: package installation failed

**Comment by ryanhum** [comment]
It's working perfectly now thank you !

**Comment by slowkow** [comment]
Hi @ryanhum, thanks for reporting the issue!

I think it should be fixed now. I deleted the unnecessary file `R/newton-example.R` in https://github.com/immunogenomics/GPROB/commit/2c33e9f4e39254bd191290db6ab38e16ca9e11a4

And now we're using GitHub Actions to test that the package can be installed.

Thanks for reporting that it works for you! That is helpful.

**Comment by rkmnl** [comment]
Thanks Kamil!
I just read the message as well as your solution.

How are you doing?

Op ma 7 jun. 2021 16:14 schreef Kamil Slowikowski ***@***.***
